name = "genengine-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[env.development]
vars = { }

[env.production]
vars = { }

# Note: Add your GEMINI_API_KEY as a secret using:
# wrangler secret put GEMINI_API_KEY